version: 0.2
env:
  parameter-store:
    APP_TOKEN: /myapp/dev/token
phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo "Token length is ${#APP_TOKEN}"
  build:
    commands:
      - mkdir -p dist
      - cp src/index.html dist/
artifacts:
  files:
    - '**/*'
  base-directory: dist
cache:
  paths:
    - 'node_modules/**/*'